"""
report_generator.py
===================
Renders the structured equity research report to PDF using reportlab.

The PDF includes:
  - Cover page with ticker, company name, date, recommendation framing
  - Each report section as drafted by the analysis engine
  - Citations rendered as inline footnotes
  - A source inventory appendix listing every [SRC-X] with title, date, URL
  - A QC summary page generated by the review layer

Author: Jovan Johansen
"""
from __future__ import annotations

import re
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Any

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, PageBreak, Table, TableStyle,
    KeepTogether,
)
from reportlab.lib.enums import TA_LEFT, TA_JUSTIFY, TA_CENTER

from data_ingestion import SourceDocument
from review_layer import QCReport


# Brand-ish palette - dark navy + gold accent
NAVY = colors.HexColor("#0B2545")
GOLD = colors.HexColor("#C9A227")
GREY_DARK = colors.HexColor("#3D3D3D")
GREY_LIGHT = colors.HexColor("#E5E5E5")


@dataclass
class ReportPayload:
    ticker: str
    company_name: str
    sector: str
    industry: str
    recommendation: str          # POSITIVE | WATCHLIST | NEUTRAL | CAUTIOUS
    market_data: Dict[str, Any]
    sections: Dict[str, str] = field(default_factory=dict)
    sources: List[SourceDocument] = field(default_factory=list)
    qc_report: QCReport = None
    generated_at: str = field(default_factory=lambda: datetime.utcnow().isoformat())


# ---------------------------------------------------------------------------
# RENDERING
# ---------------------------------------------------------------------------
class PDFReportGenerator:
    """Produces a polished institutional-style equity research PDF."""

    def __init__(self):
        self.styles = self._build_styles()

    def _build_styles(self) -> Dict[str, ParagraphStyle]:
        base = getSampleStyleSheet()
        return {
            "cover_title": ParagraphStyle(
                "CoverTitle", parent=base["Title"],
                fontSize=28, textColor=NAVY, alignment=TA_LEFT,
                spaceAfter=12, fontName="Helvetica-Bold",
            ),
            "cover_subtitle": ParagraphStyle(
                "CoverSubtitle", parent=base["Normal"],
                fontSize=14, textColor=GREY_DARK, alignment=TA_LEFT,
                spaceAfter=24,
            ),
            "section_header": ParagraphStyle(
                "SectionHeader", parent=base["Heading1"],
                fontSize=14, textColor=NAVY, fontName="Helvetica-Bold",
                spaceBefore=14, spaceAfter=8,
                borderPadding=4, leftIndent=0,
            ),
            "subsection": ParagraphStyle(
                "Subsection", parent=base["Heading2"],
                fontSize=11, textColor=NAVY, fontName="Helvetica-Bold",
                spaceBefore=8, spaceAfter=4,
            ),
            "body": ParagraphStyle(
                "Body", parent=base["BodyText"],
                fontSize=10, leading=14, alignment=TA_JUSTIFY,
                textColor=GREY_DARK, spaceAfter=8,
            ),
            "small": ParagraphStyle(
                "Small", parent=base["Normal"],
                fontSize=8, textColor=GREY_DARK, leading=10,
            ),
            "label": ParagraphStyle(
                "Label", parent=base["Normal"],
                fontSize=9, textColor=NAVY, fontName="Helvetica-Bold",
            ),
            "disclaimer": ParagraphStyle(
                "Disclaimer", parent=base["Normal"],
                fontSize=8, textColor=GREY_DARK, leading=10,
                alignment=TA_JUSTIFY, spaceBefore=10,
            ),
            "qc_pass": ParagraphStyle(
                "QCPass", parent=base["Normal"],
                fontSize=10, textColor=colors.HexColor("#0B6E4F"),
                fontName="Helvetica-Bold",
            ),
            "qc_warn": ParagraphStyle(
                "QCWarn", parent=base["Normal"],
                fontSize=10, textColor=colors.HexColor("#B23A48"),
                fontName="Helvetica-Bold",
            ),
        }

    # ---------------------------------------------------------------
    # PAGE BUILDERS
    # ---------------------------------------------------------------
    def _format_text(self, text: str) -> str:
        """Convert plain text to reportlab-safe paragraph markup."""
        # Escape XML special chars first, then re-introduce only what we need
        text = (text.replace("&", "&amp;")
                    .replace("<", "&lt;")
                    .replace(">", "&gt;"))
        # Bold the [SRC-X] citation tags so they're easy to spot
        text = re.sub(r"\[SRC-(\d+)\]",
                      r'<font color="#C9A227"><b>[SRC-\1]</b></font>', text)
        # Convert double newlines to paragraph breaks
        return text

    def _build_cover(self, payload: ReportPayload) -> List:
        story = []
        # Top color bar
        bar = Table([[""]], colWidths=[6.5 * inch], rowHeights=[0.15 * inch])
        bar.setStyle(TableStyle([("BACKGROUND", (0, 0), (-1, -1), GOLD)]))
        story.append(bar)
        story.append(Spacer(1, 0.4 * inch))

        story.append(Paragraph("EQUITY RESEARCH", self.styles["label"]))
        story.append(Spacer(1, 0.05 * inch))
        story.append(Paragraph(
            f"{payload.company_name} ({payload.ticker})",
            self.styles["cover_title"]
        ))
        story.append(Paragraph(
            f"{payload.sector} | {payload.industry}",
            self.styles["cover_subtitle"]
        ))

        # Snapshot table
        md = payload.market_data or {}
        def fmt(v, suffix=""):
            if v is None:
                return "n/a"
            try:
                return f"{float(v):,.2f}{suffix}"
            except (ValueError, TypeError):
                return str(v)

        def fmt_market_cap(v):
            if v is None:
                return "n/a"
            try:
                v = float(v)
                if v >= 1e12:
                    return f"${v / 1e12:.2f}T"
                if v >= 1e9:
                    return f"${v / 1e9:.1f}B"
                if v >= 1e6:
                    return f"${v / 1e6:.0f}M"
                return f"${v:,.0f}"
            except (ValueError, TypeError):
                return str(v)

        snapshot_rows = [
            ["Recommendation Framing", payload.recommendation],
            ["Last Price (USD)", fmt(md.get("current_price"))],
            ["Market Cap", fmt_market_cap(md.get("market_cap"))],
            ["P/E (TTM)", fmt(md.get("pe_ttm"), "x")],
            ["P/E (Forward)", fmt(md.get("pe_forward"), "x")],
            ["52-Week Range",
             f"{fmt(md.get('52w_low'))} - {fmt(md.get('52w_high'))}"],
            ["Beta (5Y Monthly)", fmt(md.get("beta"))],
            ["Report Date", datetime.utcnow().strftime("%B %d, %Y")],
        ]

        snap_table = Table(snapshot_rows, colWidths=[2.4 * inch, 3.0 * inch])
        snap_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (0, -1), GREY_LIGHT),
            ("TEXTCOLOR", (0, 0), (-1, -1), GREY_DARK),
            ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
            ("FONTNAME", (1, 0), (1, -1), "Helvetica"),
            ("FONTSIZE", (0, 0), (-1, -1), 10),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("LEFTPADDING", (0, 0), (-1, -1), 8),
            ("RIGHTPADDING", (0, 0), (-1, -1), 8),
            ("TOPPADDING", (0, 0), (-1, -1), 6),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.white),
            # Highlight the recommendation row
            ("BACKGROUND", (1, 0), (1, 0), self._rec_color(payload.recommendation)),
            ("TEXTCOLOR", (1, 0), (1, 0), colors.white),
            ("FONTNAME", (1, 0), (1, 0), "Helvetica-Bold"),
        ]))
        story.append(snap_table)

        story.append(Spacer(1, 0.4 * inch))
        story.append(Paragraph(
            "<b>Prepared by:</b> Automated Equity Research Prototype "
            "(AI-driven, human-reviewed)",
            self.styles["small"]
        ))
        story.append(Paragraph(
            "<b>Author / Reviewer:</b> Jovan Johansen | Tsunami Advisors AI Intern Case Study",
            self.styles["small"]
        ))

        story.append(Spacer(1, 0.3 * inch))
        story.append(Paragraph(
            "<b>IMPORTANT:</b> This report is research support, not investment "
            "advice. All quantitative claims are sourced to public filings or "
            "market data and tagged with [SRC-X] citations. The human analyst "
            "named above retains responsibility for the final view.",
            self.styles["disclaimer"]
        ))
        story.append(PageBreak())
        return story

    @staticmethod
    def _rec_color(rec: str) -> colors.Color:
        rec_clean = rec.upper().strip()
        if "POSITIVE" in rec_clean:
            return colors.HexColor("#0B6E4F")
        if "WATCHLIST" in rec_clean:
            return colors.HexColor("#1B6CA8")
        if "CAUTIOUS" in rec_clean:
            return colors.HexColor("#B23A48")
        return colors.HexColor("#6C757D")  # neutral grey

    def _build_section(self, title: str, body_text: str) -> List:
        elements = [Paragraph(title, self.styles["section_header"])]
        # Split on double newlines, preserve paragraph breaks
        paragraphs = re.split(r"\n\s*\n", body_text.strip())
        for p in paragraphs:
            p = p.strip()
            if not p:
                continue
            # Subsection headers - lines that are SHORT and ALL CAPS
            if len(p) < 60 and p.isupper() and ":" not in p[:5]:
                elements.append(Paragraph(p, self.styles["subsection"]))
            elif p.endswith(":") and len(p) < 60:
                elements.append(Paragraph(p, self.styles["subsection"]))
            else:
                # Normalize internal newlines
                p = p.replace("\n", " ")
                p = self._format_text(p)
                elements.append(Paragraph(p, self.styles["body"]))
        return elements

    def _build_sources_appendix(self, sources: List[SourceDocument]) -> List:
        story = [PageBreak(),
                 Paragraph("APPENDIX A: SOURCE INVENTORY", self.styles["section_header"]),
                 Paragraph(
                     "Every [SRC-X] citation in this report maps to one of the "
                     "documents below. URLs link to the original public source.",
                     self.styles["body"]
                 ),
                 Spacer(1, 0.1 * inch)]

        rows = [["ID", "Type", "Title", "Date", "Source URL"]]
        for s in sources:
            url_short = s.url if len(s.url) <= 60 else s.url[:57] + "..."
            rows.append([s.source_id, s.source_type, s.title[:38],
                         s.publication_date, url_short])

        table = Table(rows, colWidths=[0.55 * inch, 0.85 * inch, 1.95 * inch,
                                       0.85 * inch, 2.6 * inch])
        table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), NAVY),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, 0), 9),
            ("FONTSIZE", (0, 1), (-1, -1), 8),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("GRID", (0, 0), (-1, -1), 0.3, GREY_LIGHT),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1),
             [colors.white, GREY_LIGHT]),
            ("LEFTPADDING", (0, 0), (-1, -1), 4),
            ("RIGHTPADDING", (0, 0), (-1, -1), 4),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ]))
        story.append(table)
        return story

    def _build_qc_appendix(self, qc: QCReport) -> List:
        if qc is None:
            return []
        story = [PageBreak(),
                 Paragraph("APPENDIX B: QUALITY CONTROL SUMMARY",
                           self.styles["section_header"]),
                 Paragraph(
                     "This page documents automated checks applied to the draft. "
                     "It does not replace human review.",
                     self.styles["body"]
                 ),
                 Spacer(1, 0.1 * inch)]

        severity_style = (
            self.styles["qc_pass"] if qc.overall_severity == "low"
            else self.styles["qc_warn"]
        )
        story.append(Paragraph(
            f"Overall severity: {qc.overall_severity.upper()}",
            severity_style
        ))
        story.append(Paragraph(
            f"Citation coverage: {qc.citation_coverage_pct}%",
            self.styles["body"]
        ))
        story.append(Paragraph(
            f"Ready for human review: {qc.ready_for_human_review}",
            self.styles["body"]
        ))
        story.append(Spacer(1, 0.1 * inch))

        if qc.invalid_citations:
            story.append(Paragraph("Invalid citations detected:",
                                   self.styles["subsection"]))
            for tag in qc.invalid_citations:
                story.append(Paragraph(f"&bull; {tag}", self.styles["body"]))

        if isinstance(qc.llm_review, dict):
            for key, label in [
                ("potentially_hallucinated_facts", "Potential hallucinations flagged"),
                ("tone_or_compliance_issues", "Tone / compliance issues"),
                ("internal_inconsistencies", "Internal inconsistencies"),
                ("missing_required_elements", "Missing required elements"),
            ]:
                items = qc.llm_review.get(key, []) or []
                if items:
                    story.append(Paragraph(label + ":", self.styles["subsection"]))
                    for item in items[:6]:
                        story.append(Paragraph(f"&bull; {item}",
                                               self.styles["body"]))

        if qc.suspicious_uncited_numbers:
            story.append(Paragraph(
                f"Quantitative claims flagged for missing citations "
                f"({len(qc.suspicious_uncited_numbers)} found):",
                self.styles["subsection"]
            ))
            for s in qc.suspicious_uncited_numbers[:8]:
                story.append(Paragraph(f"&bull; {s}", self.styles["body"]))

        story.append(Spacer(1, 0.2 * inch))
        story.append(Paragraph(
            "Human reviewer sign-off line: ____________________________  "
            "Date: ____________",
            self.styles["small"]
        ))
        return story

    # ---------------------------------------------------------------
    # PUBLIC ENTRY POINT
    # ---------------------------------------------------------------
    def generate(self, payload: ReportPayload, output_path: Path):
        doc = SimpleDocTemplate(
            str(output_path), pagesize=letter,
            leftMargin=0.7 * inch, rightMargin=0.7 * inch,
            topMargin=0.6 * inch, bottomMargin=0.6 * inch,
        )
        story = []
        story += self._build_cover(payload)

        section_order = [
            ("company_overview", "1. COMPANY SNAPSHOT"),
            ("performance", "2. FINANCIAL PERFORMANCE SUMMARY"),
            ("drivers_risks", "3. KEY DRIVERS AND RISKS"),
            ("news_highlights", "4. EARNINGS & MANAGEMENT COMMENTARY"),
            ("thesis", "5. INVESTMENT THESIS AND OUTLOOK"),
        ]
        for key, title in section_order:
            body = payload.sections.get(key)
            if body:
                story += self._build_section(title, body)

        story += self._build_sources_appendix(payload.sources)
        story += self._build_qc_appendix(payload.qc_report)

        # Footer-style closing disclaimer
        story.append(Spacer(1, 0.2 * inch))
        story.append(Paragraph(
            "DISCLAIMER: This document was generated by an AI-driven research "
            "prototype for educational and research-support purposes. It is "
            "not investment advice, not a solicitation, and not a guarantee "
            "of accuracy. All recommendations require human analyst review "
            "and sign-off before use. Past performance does not indicate "
            "future results.",
            self.styles["disclaimer"]
        ))

        doc.build(story, onFirstPage=self._page_decoration,
                  onLaterPages=self._page_decoration)

    @staticmethod
    def _page_decoration(canvas, doc):
        """Adds a thin footer to every page."""
        canvas.saveState()
        canvas.setStrokeColor(GREY_LIGHT)
        canvas.setLineWidth(0.5)
        canvas.line(0.7 * inch, 0.5 * inch, 7.8 * inch, 0.5 * inch)
        canvas.setFont("Helvetica", 7)
        canvas.setFillColor(GREY_DARK)
        canvas.drawString(0.7 * inch, 0.35 * inch,
                          "Automated Equity Research Prototype | "
                          "Tsunami Advisors AI Intern Case Study")
        canvas.drawRightString(7.8 * inch, 0.35 * inch,
                               f"Page {doc.page}")
        canvas.restoreState()
